on: [push]

jobs:
  test_job:
    runs-on: macOS-latest
    name: A job to test the GitHub fastlane action
    steps:
    - uses: actions/checkout@v1
    - name: Fastlane step
      uses: maierj/fastlane-action@master
      with:
        lane: 'beta'
