on: [push]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14]
    name: A job to test the GitHub fastlane action
    steps:
    - uses: actions/checkout@v1
    - name: Fastlane step (root directory)
      uses: maierj/fastlane-action@gemfile-usage
      with:
        lane: 'beta'
        options: '{ "option1": "value1", "option2": "value2" }'
      env:
        ENV_VARIABLE_1: VALUE_1
        ENV_VARIABLE_2: VALUE_2
    - name: Fastlane step (subdirectory)
      uses: maierj/fastlane-action@gemfile-usage
      with:
        lane: 'beta'
        subdirectory: 'ios'
      env:
        ENV_VARIABLE_1: VALUE_1
        ENV_VARIABLE_2: VALUE_2
