on: [push]

jobs:
  test_job:
    runs-on: macOS-latest
    name: A job to test the GitHub fastlane action
    steps:
    - name: Hello world action step
      uses: maierj/fastlane-action/github-fastlane-action@master
      with:
        lane: 'beta'
