on: [push]

jobs:
  test_job:
    runs-on: macOS-latest
    name: A job to test the GitHub fastlane action
    steps:
    - uses: actions/checkout@v1
    - name: Fastlane step (root directory)
      uses: maierj/fastlane-action@master
      with:
        lane: 'beta'
        options: '{ "option1": "value1", "option2": "value2" }'
    - name: Fastlane step (subdirectory)
      uses: maierj/fastlane-action@master
      with:
        lane: 'beta'
        subdirectory: 'ios'
